# Generated by Django 5.0.6 on 2024-05-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='staus',
            new_name='status',
        ),
    ]
