# Generated by Django 5.0.6 on 2024-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_staus_cart_status_rename_staus_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='added', max_length=200),
        ),
    ]
